# Generated by Django 5.0 on 2024-01-19 11:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("firebase_uid", models.CharField(max_length=128)),
                ("name", models.CharField(max_length=510)),
                ("email", models.EmailField(max_length=254)),
                ("username", models.CharField(max_length=255)),
                ("email_verified", models.BooleanField(default=False)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("photo_url", models.URLField(blank=True, null=True)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("firebase", "Firebase"),
                            ("discord", "Discord"),
                            ("email", "Email"),
                            ("anonymous", "Anonymous"),
                        ],
                        default="firebase",
                        max_length=255,
                    ),
                ),
                ("address", models.TextField(blank=True, null=True)),
                ("state", models.CharField(blank=True, max_length=255, null=True)),
                ("country", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
    ]
